from pathlib import Path
import sys
import cmath
import math
import py5

PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

from lib.preview import maybe_save_exit_on_frame
from lib.sizes import get_sizes
from lib.paths import sketch_dir
SKETCH_DIR = sketch_dir(__file__)
PREVIEW_FRAME = 60

PREVIEW_SIZE, OUTPUT_SIZE, SIZE = get_sizes()

# Theme: "Quasicrystal" — Penrose P3 aperiodic rhombus tiling; two rhombus
# shapes (fat 72° and thin 36°) generated by 7 rounds of triangle substitution
# from a decagonal seed; 5-fold orientation coloring reveals hidden quasiperiodic order.

PHI    = (1 + math.sqrt(5)) / 2   # golden ratio
N_ITER = 7                         # subdivision iterations → ~6100 triangles

BG_COL   = (5, 8, 15)
EDGE_COL = (12, 10, 22)
EDGE_W   = 0.6

# 5 warm tones  (fat  rhombus halves — type 0)
WARM = [
    (228, 162,  28),   # gold
    (212,  88,  42),   # coral
    (205, 178,  55),   # warm yellow
    (224, 118,  35),   # amber
    (232, 148,  58),   # light amber
]
# 5 cool tones  (thin rhombus halves — type 1)
COOL = [
    ( 28, 152, 205),   # cerulean
    ( 42, 188, 162),   # teal
    ( 62, 112, 212),   # violet-blue
    ( 22, 172, 138),   # green-teal
    ( 82, 132, 222),   # periwinkle
]


def subdivide(triangles):
    result = []
    for color, A, B, C in triangles:
        if color == 0:              # fat acute triangle  (36° apex at A)
            P = A + (B - A) / PHI
            result.append((0, C, P, B))
            result.append((1, P, C, A))
        else:                       # thin obtuse triangle (108° apex at A)
            Q = B + (A - B) / PHI
            R = B + (C - B) / PHI
            result.append((1, R, C, A))
            result.append((1, Q, R, B))
            result.append((0, R, Q, A))
    return result


def setup():
    py5.size(*SIZE)
    W, H = SIZE

    # Decagonal seed: 10 fat triangles arranged around the origin
    triangles = []
    for i in range(10):
        B = cmath.rect(1, (2 * i - 1) * math.pi / 10)
        C = cmath.rect(1, (2 * i + 1) * math.pi / 10)
        if i % 2 == 0:
            B, C = C, B
        triangles.append((0, 0j, B, C))

    for _ in range(N_ITER):
        triangles = subdivide(triangles)

    all_pts = [pt for _, A, B, C in triangles for pt in (A, B, C)]
    xs = [p.real for p in all_pts]
    ys = [p.imag for p in all_pts]
    x_min, x_max = min(xs), max(xs)
    y_min, y_max = min(ys), max(ys)

    scale = min(W * 0.90 / (x_max - x_min + 1e-8),
                H * 0.90 / (y_max - y_min + 1e-8))
    ox = W / 2 - (x_min + x_max) / 2 * scale
    oy = H / 2 - (y_min + y_max) / 2 * scale

    def to_screen(z):
        return z.real * scale + ox, z.imag * scale + oy

    py5.background(*BG_COL)
    py5.no_stroke()

    for color, A, B, C in triangles:
        centroid = (A + B + C) / 3
        sector = int((cmath.phase(centroid) + math.pi) / (2 * math.pi / 5)) % 5
        col = WARM[sector] if color == 0 else COOL[sector]
        py5.fill(*col)
        ax, ay = to_screen(A)
        bx, by = to_screen(B)
        cx, cy = to_screen(C)
        py5.begin_shape()
        py5.vertex(ax, ay)
        py5.vertex(bx, by)
        py5.vertex(cx, cy)
        py5.end_shape(py5.CLOSE)

    py5.no_fill()
    py5.stroke(*EDGE_COL)
    py5.stroke_weight(EDGE_W)
    for _, A, B, C in triangles:
        ax, ay = to_screen(A)
        bx, by = to_screen(B)
        cx, cy = to_screen(C)
        py5.begin_shape()
        py5.vertex(ax, ay)
        py5.vertex(bx, by)
        py5.vertex(cx, cy)
        py5.end_shape(py5.CLOSE)


def draw():
    maybe_save_exit_on_frame(PREVIEW_FRAME, SKETCH_DIR, filename="preview.png")


py5.run_sketch()
