from pathlib import Path
import shutil
import subprocess
import sys
import random
import numpy as np
import py5

PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

from lib.paths import sketch_dir
from lib.sizes import get_sizes

SKETCH_DIR = sketch_dir(__file__)
WORK_NAME = SKETCH_DIR.name
FRAMES_DIR = SKETCH_DIR / "frames"
DURATION_SEC = 18
FPS = 60
TOTAL_FRAMES = DURATION_SEC * FPS
PREVIEW_FILENAME = f"{WORK_NAME}_p1.png"
PREVIEW_SIZE, OUTPUT_SIZE, _ = get_sizes()
SIZE = OUTPUT_SIZE

# Fluid Simulation Grid (16:9 aspect ratio)
Nx, Ny = 480, 270
x = np.linspace(0, Nx - 1, Nx, dtype=np.float32)
y = np.linspace(0, Ny - 1, Ny, dtype=np.float32)
X_grid, Y_grid = np.meshgrid(x, y)

# Vorticity and Streamfunction fields
omega = np.zeros((Ny, Nx), dtype=np.float32)
psi_stream = np.zeros((Ny, Nx), dtype=np.float32)
u = np.zeros((Ny, Nx), dtype=np.float32)
v = np.zeros((Ny, Nx), dtype=np.float32)

# Initial cell concentration: dense algal layer at the top surface
Y_norm = y[:, None] / Ny
C = np.tile(np.exp(- (Y_norm / 0.12)**2).astype(np.float32) * 1.5, (1, Nx))

# Multi-frequency perturbation triggering bioconvective Rayleigh-Taylor fingers
for freq in [3, 5, 8, 11]:
    phase = random.uniform(0.0, 2.0 * np.pi)
    amp = random.uniform(0.05, 0.09)
    C += amp * np.sin(2.0 * np.pi * freq * x / Nx + phase)[None, :] * C

dt = 0.60

# RGBA pixel buffer for simulation rendering (py5 ARGB format: 0=Alpha, 1=Red, 2=Green, 3=Blue)
pixel_buffer = np.zeros((Ny, Nx, 4), dtype=np.uint8)
pixel_buffer[..., 0] = 255

# Bioluminescent Swimmer Particles
MAX_PARTICLES = 220
particles = []


class SwimmerParticle:
    def __init__(self, px, py):
        self.px = px
        self.py = py
        self.vx = 0.0
        self.vy = 0.0
        self.life = random.uniform(50.0, 120.0)
        self.max_life = self.life
        self.swim_phase = random.uniform(0.0, 2.0 * np.pi)
        self.swim_speed = random.uniform(0.8, 1.6)
        self.brightness = 0.0

    def update(self, u_field, v_field):
        gx = int(np.clip(self.px * (Nx / py5.width), 0, Nx - 1))
        gy = int(np.clip(self.py * (Ny / py5.height), 0, Ny - 1))

        fluid_u = u_field[gy, gx] * (py5.width / Nx) * 1.1
        fluid_v = v_field[gy, gx] * (py5.height / Ny) * 1.1

        # Upward gyrotactic steering with gentle undulating wiggle
        self.swim_phase += 0.14
        swim_dx = np.cos(self.swim_phase) * self.swim_speed * 0.35
        swim_dy = - self.swim_speed + np.sin(self.swim_phase) * self.swim_speed * 0.25

        self.vx = self.vx * 0.82 + (fluid_u + swim_dx) * 0.18
        self.vy = self.vy * 0.82 + (fluid_v + swim_dy) * 0.18

        self.px += self.vx
        self.py += self.vy

        # Shear stress induces bioluminescent flash
        local_shear = abs(fluid_u) + abs(fluid_v)
        target_bright = np.clip(local_shear * 0.20, 0.0, 1.0)
        self.brightness = self.brightness * 0.90 + target_bright * 0.10

        self.life -= 1.0

    @property
    def is_dead(self):
        return (self.life <= 0 or self.px < -20 or self.px > py5.width + 20 or
                self.py < -10 or self.py > py5.height + 20)


def setup():
    py5.size(*SIZE)
    py5.pixel_density(1)
    FRAMES_DIR.mkdir(exist_ok=True)


def update_bioconvection_physics():
    global omega, psi_stream, u, v, C

    # 1. Fast Jacobi relaxation for Stream Function: Laplacian(psi) = -omega
    # Boundary conditions: psi = 0 at top (y=0) and bottom (y=Ny-1), periodic in x
    for _ in range(25):
        psi_stream[1:-1, :] = 0.25 * (
            psi_stream[2:, :] + psi_stream[:-2, :] +
            np.roll(psi_stream[1:-1, :], 1, axis=1) + np.roll(psi_stream[1:-1, :], -1, axis=1) +
            omega[1:-1, :]
        )

    # Fluid velocity from stream function (divergence-free flow)
    u_inner = (psi_stream[2:, :] - psi_stream[:-2, :]) * 0.5
    u = np.pad(u_inner, ((1, 1), (0, 0)), mode='edge')
    v = -(np.roll(psi_stream, -1, axis=1) - np.roll(psi_stream, 1, axis=1)) * 0.5
    v[0, :] = 0.0
    v[-1, :] = 0.0

    # 2. Buoyancy torque generated by horizontal density gradients (dC/dx)
    dC_dx = (np.roll(C, -1, axis=1) - np.roll(C, 1, axis=1)) * 0.5
    omega[1:-1, :] += dt * (1.85 * dC_dx[1:-1, :] - 0.042 * omega[1:-1, :])

    # Viscous vorticity diffusion
    lap_omega = (np.roll(omega, 1, axis=1) + np.roll(omega, -1, axis=1) +
                 np.pad(omega[2:, :] + omega[:-2, :], ((1, 1), (0, 0)), mode='edge') - 4.0 * omega)
    omega += 0.02 * lap_omega

    # 3. Semi-Lagrangian Advection for microbial concentration field
    # Upward active swimming (cells swim towards surface y=0: v_swim = -0.34)
    vx_eff = u
    vy_eff = v - 0.34
    vy_eff[0, :] = 0.0  # Surface boundary

    src_x = np.mod(X_grid - vx_eff * dt, Nx)
    src_y = np.clip(Y_grid - vy_eff * dt, 0, Ny - 1)

    x0 = np.clip(np.floor(src_x).astype(int), 0, Nx - 1)
    x1 = np.mod(x0 + 1, Nx)
    y0 = np.clip(np.floor(src_y).astype(int), 0, Ny - 1)
    y1 = np.clip(y0 + 1, 0, Ny - 1)

    wx = src_x - x0
    wy = src_y - y0

    C_adv = (1.0 - wx) * (1.0 - wy) * C[y0, x0] + \
            wx * (1.0 - wy) * C[y0, x1] + \
            (1.0 - wx) * wy * C[y1, x0] + \
            wx * wy * C[y1, x1]

    # Gentle bio-diffusion to preserve silken plume filaments
    lap_C = (np.roll(C_adv, 1, axis=1) + np.roll(C_adv, -1, axis=1) +
             np.pad(C_adv[2:, :] + C_adv[:-2, :], ((1, 1), (0, 0)), mode='edge') - 4.0 * C_adv)
    C = np.clip(C_adv + 0.012 * lap_C, 0.0, 2.5)


def render_bioconvection_field():
    global C, omega, pixel_buffer

    # 1. Base Abyssal Midnight Navy: #020813 (2, 8, 19)
    r = np.full_like(C, 2.0)
    g = np.full_like(C, 8.0)
    b = np.full_like(C, 19.0)

    # 2. Bioluminescent Algal Emerald & Jade (60% dominant): #0da868
    emerald = np.clip(C / 0.36, 0.0, 1.0)**1.3
    r += emerald * 12.0
    g += emerald * 172.0
    b += emerald * 102.0

    # 3. Fluorescent Electric Cyan Plume Tendrils (30% secondary): #26d9d0
    cyan = np.clip((C - 0.24) / 0.34, 0.0, 1.0)**1.5
    r += cyan * 36.0
    g += cyan * 215.0
    b += cyan * 205.0

    # 4. Solar Amber Phototaxis Cores (10% accent): #f5b838
    amber = np.clip((C - 0.44) / 0.36, 0.0, 1.0)**2.2
    r += amber * 245.0
    g += amber * 182.0
    b += amber * 54.0

    # Recirculating vortex eye glow
    vort_glow = np.clip(np.abs(omega) * 0.48, 0.0, 1.0)**1.6
    r += vort_glow * 25.0
    g += vort_glow * 65.0
    b += vort_glow * 140.0

    # Plume edge rim-lighting via gradient of C
    gc_x = (np.roll(C, -1, axis=1) - np.roll(C, 1, axis=1)) * 0.5
    gc_y = (np.roll(C, -1, axis=0) - np.roll(C, 1, axis=0)) * 0.5
    edge_sheen = np.clip(np.sqrt(gc_x**2 + gc_y**2) * 2.0, 0.0, 1.0)
    r += edge_sheen * 20.0
    g += edge_sheen * 85.0
    b += edge_sheen * 110.0

    pixel_buffer[..., 0] = 255
    pixel_buffer[..., 1] = np.clip(r, 0, 255).astype(np.uint8)
    pixel_buffer[..., 2] = np.clip(g, 0, 255).astype(np.uint8)
    pixel_buffer[..., 3] = np.clip(b, 0, 255).astype(np.uint8)


def draw_frame():
    global particles

    # Advance fluid dynamics
    update_bioconvection_physics()

    # Render pixel field
    render_bioconvection_field()

    # Draw fluid simulation image upscaled to 4K canvas
    img = py5.create_image(Nx, Ny, py5.ARGB)
    img.load_np_pixels()
    if img.np_pixels is not None:
        img.np_pixels[:] = pixel_buffer
        img.update_np_pixels()
    else:
        a = pixel_buffer[..., 0].astype(np.int32)
        r = pixel_buffer[..., 1].astype(np.int32)
        g = pixel_buffer[..., 2].astype(np.int32)
        b = pixel_buffer[..., 3].astype(np.int32)
        img.pixels[:] = (a << 24) | (r << 16) | (g << 8) | b
        img.update_pixels()

    py5.image(img, 0, 0, py5.width, py5.height)

    # Spawn replacement swimmer particles in plume regions
    if len(particles) < MAX_PARTICLES:
        high_cells = np.argwhere(C > 0.22)
        if len(high_cells) > 0:
            num_spawn = min(12, MAX_PARTICLES - len(particles))
            picks = np.random.choice(len(high_cells), size=num_spawn, replace=True)
            for idx in picks:
                gy, gx = high_cells[idx]
                spx = (gx / Nx) * py5.width + random.uniform(-4.0, 4.0)
                spy = (gy / Ny) * py5.height + random.uniform(-4.0, 4.0)
                particles.append(SwimmerParticle(spx, spy))

    # Render Bioluminescent Swimmer Particles at 4K resolution
    py5.blend_mode(py5.ADD)
    active_particles = []
    for p in particles:
        p.update(u, v)
        if not p.is_dead:
            active_particles.append(p)
            life_norm = p.life / p.max_life
            alpha = int(life_norm * (100 + 130 * p.brightness))

            # Color shifts from cyan to solar gold under shear excitement
            cr = int(36 + p.brightness * 210)
            cg = int(218 + p.brightness * 25)
            cb = int(205 - p.brightness * 150)

            # Outer aura
            py5.no_stroke()
            py5.fill(cr, cg, cb, int(alpha * 0.25))
            py5.circle(p.px, p.py, 3.5 + p.brightness * 2.5)

            # Glowing nucleus
            py5.fill(cr, cg, cb, int(alpha * 0.8))
            py5.circle(p.px, p.py, 1.4 + p.brightness * 1.0)

            # Motion trail vector
            py5.stroke(cr, cg, cb, int(alpha * 0.35))
            py5.stroke_weight(1.0)
            py5.line(p.px, p.py, p.px - p.vx * 1.8, p.py - p.vy * 1.8)

    particles = active_particles
    py5.blend_mode(py5.BLEND)

    # Fail-safe check
    if py5.frame_count == 2 or py5.frame_count % 60 == 0:
        py5.load_np_pixels()
        if py5.np_pixels.std() < 1.0:
            print(f"[Error] Blank screen detected on frame {py5.frame_count} (std < 1.0). Aborting.")
            import os
            os._exit(1)

    # Save animation frame
    py5.save_frame(str(FRAMES_DIR / "frame-####.png"))

    if py5.frame_count % 60 == 0:
        progress_pct = (py5.frame_count / TOTAL_FRAMES) * 100.0
        print(f"[Render Progress] Frame {py5.frame_count}/{TOTAL_FRAMES} ({progress_pct:.1f}%) | Active Swimmers: {len(particles)}")

    # Finalize render
    if py5.frame_count >= TOTAL_FRAMES:
        py5.exit_sketch()

        print(f"[Render FFmpeg] Compiling {TOTAL_FRAMES} frames into video...")
        mp4_path = SKETCH_DIR / f"{WORK_NAME}.mp4"
        output_mp4 = SKETCH_DIR / "output.mp4"
        subprocess.run([
            "ffmpeg", "-y", "-r", str(FPS),
            "-i", str(FRAMES_DIR / "frame-%04d.png"),
            "-vcodec", "libx264", "-pix_fmt", "yuv420p",
            "-crf", "18", str(mp4_path),
        ], check=True)
        shutil.copyfile(mp4_path, output_mp4)

        # Save preview snapshot from midpoint
        mid = str(FRAMES_DIR / f"frame-{TOTAL_FRAMES // 2:04d}.png")
        subprocess.run(["cp", mid, str(SKETCH_DIR / PREVIEW_FILENAME)], check=True)

        # Clean up temporary frames directory
        if FRAMES_DIR.exists():
            shutil.rmtree(FRAMES_DIR)
            print("[Render Cleanup] Temporary frames directory successfully removed.")

        import os
        os._exit(0)


def draw():
    try:
        draw_frame()
    except Exception as e:
        import traceback
        traceback.print_exc()
        import os
        os._exit(1)


py5.run_sketch()
